version: '3.8'
services:
  # frontend:

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass 
      - POSTGRES_DB=my_db
    
  
  api:
    build: ./server
    restart: always
    ports:
      - "3003:3003"
    environment:
      - POSTGRES_CONNECTION_STRING=postgresql://postgres:pass@database/my_db
      - NODE_ENV=production
    depends_on:
      - database
