version: '3.8'
services:
  # frontend:

  api:
    build: ./server
    ports:
      - 3003:3003
    environment:
      - POSTGRES_CONNECTION_STRING=postgresql://user:pass@127.0.0.1:5432/my_db
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_PASSWORD=pass 
      - POSTGRES_USER=user
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
