version: '3.8'
services:

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass 
      - POSTGRES_DB=my_db
    volumes:
      - pgdatasource:/var/lib/postgresql/data
    
  
  api:
    build: ./server
    ports:
      - "3003:3003"
    environment:
      - POSTGRES_CONNECTION_STRING=postgresql://postgres:pass@database/my_db
      - NODE_ENV=production
    depends_on:
      - database
    restart: always

  frontend:
    build: ./client
    ports:
      - "3004:3004"
    depends_on:
      - api
volumes:
  pgdatasource: