version: '3.8'
services:
  # frontend:

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_PASSWORD=pass 
      - POSTGRES_USER=user
    volumes:
      - ./server/postgres-data:/var/lib/postgresql/data
  
  api:
    build: ./server
    ports:
      - "3003:3003"
    environment:
      - POSTGRES_CONNECTION_STRING=postgresql://user:pass@database/my_db
      - NODE_ENV=production
    depends_on:
      - database
